campaign:
    base_domain: localhost:8001
    url_scheme: http
    subdomain_mode: true
email_scheduler:
    enabled: true
    poll_interval_seconds: 15
    emails_per_minute: 60
    batch_size: 25
    batch_pause_ms: 1000
    max_parallel_campaigns: 3
security:
    jwt_secret: ba200585e2b34479fa650700672e1247bb5c255aa6c75228a2f7fc899dfb66d0
    test_mode_token: 1696e7fb-75a5-4bac-a6b0-e16025fe32a5
server:
    api_port: 8088
    campaign_port: 8001
    dashboard_port: 8000
    host: 0.0.0.0
session:
    cookie_domain: ""
    cookie_http_only: true
    cookie_name: fp_session
    cookie_secure: false
    ttl: 24h
template_assets_dir: templates/assets
template_dir: templates
